config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :students
  resources :registrations
  resources :families
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :camps
  resources :camp_instructors
  resources :curriculums
  resources :instructors
  resources :locations
  
  get 'home', :to => 'home#home'
  get 'about', :to => 'home#about'
  get 'contact', :to => 'home#contact'
  get 'privacy', :to => 'home#privacy'
  
  root to: 'home#home'

end

app/models/camp.rb
class Camp < ApplicationRecord
  # relationships
  belongs_to :curriculum
  belongs_to :location
  has_many :camp_instructors
  has_many :instructors, through: :camp_instructors
  has_many :registrations
  has_many :students, through: :registrations

  # validations
  validates_presence_of :location_id, :curriculum_id, :time_slot, :start_date
  validates_numericality_of :cost, greater_than_or_equal_to: 0
  validates_date :start_date, :on_or_after => lambda { Date.today }, :on_or_after_message => "cannot be in the past", on:  :create
  validates_date :end_date, :on_or_after => :start_date
  validates_inclusion_of :time_slot, in: %w[am pm], message: "is not an accepted time slot"
  validates_numericality_of :max_students, only_integer: true, greater_than: 0, allow_blank: true
  validate :curriculum_is_active_in_the_system
  validate :location_is_active_in_the_system
  validate :camp_is_not_a_duplicate, on: :create
  validate :max_students_not_greater_than_capacity

  # scopes
  scope :alphabetical, -> { joins(:curriculum).order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :chronological, -> { order('start_date','end_date') }
  scope :morning, -> { where('time_slot = ?','am') }
  scope :afternoon, -> { where('time_slot = ?','pm') }
  scope :upcoming, -> { where('start_date >= ?', Date.today) }
  scope :past, -> { where('end_date < ?', Date.today) }
  scope :for_curriculum, ->(curriculum_id) { where("curriculum_id = ?", curriculum_id) }
  scope :full, -> { joins(:registrations).group(:camp_id).having('count(*) = max_students') }
  
    # instance methods
  def name
    self.curriculum.name
  end

  def already_exists?
    Camp.where(time_slot: self.time_slot, start_date: self.start_date, location_id: self.location_id).size == 1
  end

  # callbacks
  before_update :remove_instructors_from_inactive_camp

  # private
  def curriculum_is_active_in_the_system
    return if self.curriculum.nil?
    errors.add(:curriculum, "is not currently active") unless self.curriculum.active
  end

  def location_is_active_in_the_system
    return if self.location.nil?
    errors.add(:location, "is not currently active") unless self.location.active
  end

  def camp_is_not_a_duplicate
    return true if self.time_slot.nil? || self.start_date.nil? || self.location_id.nil?
    if self.already_exists?
      errors.add(:time_slot, "already exists for start date, time slot and location")
    end
  end

  def max_students_not_greater_than_capacity
    return true if self.max_students.nil? || self.location_id.nil?
    if self.max_students > self.location.max_capacity
      errors.add(:max_students, "is greater than the location capacity")
    end
  end

  def remove_instructors_from_inactive_camp
    # confirm that camp is marked as inactive
    if !self.active
      self.camp_instructors.each{|ci| ci.destroy}
    end
  end
  
  # def is_full?
  #   self.max_students == self.registrations.count
  # end
  
  # def enrollment
  #   self.registrations.count
  # end
  
  
  
  
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  def index
    @active_camps = Camp.all.active.alphabetical.paginate(:page => params[:active_camps]).per_page(10)
    @inactive_camps = Camp.all.inactive.alphabetical.paginate(:page => params[:inactive_camps]).per_page(1)
  end

  def show
    @instructors = @camp.instructors.alphabetical
  end

  def edit
  end

  def new
    @camp = Camp.new
  end

  def create
    @camp = Camp.new(camp_params)
    if @camp.save
      redirect_to camp_path(@camp), notice: "#{@camp.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    @camp.update(camp_params)
    if @camp.save
      redirect_to camp_path(@camp), notice: "#{@camp.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @camp.destroy
    redirect_to camps_url, notice: "#{@camp.name} was removed from the system."
  end

  private
    def set_camp
      @camp = Camp.find(params[:id])
    end

    def camp_params
      params.require(:camp).permit(:curriculum_id, :location_id, :cost, :start_date, :end_date, :time_slot, :max_students, :active)
    end
end

app/views/camps/_active_camps.html.erb
<% if @active_camps.empty? %>
  <h3>There are no camps in the system at this time</h3>
<% else %>
  <h3>Active Camps</h3>

  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>Time Slot</th>
      <th>Max Students</th>
      <th>Remaining Slots</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_camps.active.each do |camp| %>
      <tr>
        <td><%= link_to camp.curriculum.name, camp %></td>
        <td><%= camp.start_date.strftime("%m/%d/%y") %></td>
        <td><%= camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
        <td><%= camp.max_students %></td>
        <td><%# camp.max_students - camp.registrations.count %></td>
        <td><%= link_to 'Edit', edit_camp_path(camp), :class=>"btn waves-effect waves-light blue" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<% end %>

<span class="paginate">
  <%= will_paginate @active_camps, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => 'active_camps' %>
</span>

app/views/camps/_camp_details.html.erb
<div class="card indigo lighten-2">
  <div class="card-content white-text">
  Camp Details
    <span class="card-title"><%=@camp.curriculum.name%></span>

    <p><%= @camp.curriculum.description %></p>

    <h5>Basic Information</h5>
    <p><strong>Location: </strong><%= @camp.location.name %></p>
    <p><strong>Dates: </strong><%= @camp.start_date.strftime("%m/%d/%y") %> - <%= @camp.end_date.strftime("%m/%d/%y") %></p>
    <p><strong>Time of Day: </strong><%= @camp.time_slot == "am" ? "Morning" : "Afternoon" %></p>
    <p><strong>Chess Levels: </strong><%= @camp.curriculum.min_rating %> - <%= @camp.curriculum.max_rating %></p>
    <p><strong>Max Enrollment: </strong><%= @camp.max_students %></p>
    <p><strong>Active: </strong><%= @camp.active ? "camp is currently active" : "camp is currently inactive." %></p>
    <p><strong>Camp: </strong>$<%= @camp.cost %>0</p>
    <p><strong>Slots Remaining: </strong><%# @camp.max_students - @camp.registrations.count %></p>
  </div>
  <div class="card-action">
    <%= link_to 'Edit', edit_camp_path(@camp), :class=>"btn waves-effect waves-light blue" %>
    <%= link_to 'Back', camps_path, :class=>"btn waves-effect waves-light blue" %>
  </div>
</div>

app/views/camps/_camp_instructors.html.erb
<div class="card indigo lighten-2">
  <div class="card-content white-text">
    <span class="card-title">Camp Instructors</span>
	  <% if @instructors.empty? %>
		<p>No instructors at this time</p>
	  <% else %>
      <ul>
        <% @instructors.each do |i| %>
          <li>
            <%= link_to(camp_instructor_path(id: camp_instructor_id_for(@camp, i)), method: :delete, class: 'remove') do %>
              x&nbsp;&nbsp;
            <% end %>
            <%= link_to i.proper_name, instructor_path(i) %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div class="card-action">
    <%= link_to "Add a new instructor", new_camp_instructor_path(camp_id: @camp.id) %>
    </div>
  </div>
</div>

app/views/camps/_camp_students.html.erb
<div class="col s12 m6">
  <div class="card indigo lighten-2">
    <div class="card-content white-text">
      <span class="card-title">Registered Students</span>
      <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Points Earned</th>
        </tr>
      </thead>

      <tbody>
         @camp.registrations.each do |r| 
          <tr>
            <td>r.student.proper_name</td>
            <td>r.points_earned</td>
          </tr>
        end
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/camps/_form.html.erb
<%= simple_form_for(@camp) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :location_id, collection: Location.alphabetical.active.to_a, include_blank: true %>
      <%= f.input :curriculum_id, collection: Curriculum.alphabetical.active.to_a, include_blank: true %>
      <%= f.input :cost, label_html: { class: 'active' } %>
      <%= f.input :time_slot, collection: [["Morning","am"],["Afternoon","pm"]], include_blank: true %>
      <%= f.input :start_date, label_html: { class: 'active'} %>
      <%= f.input :end_date, label_html: { class: 'active' } %>
      <%= f.input :max_students, label_html: { class: 'active' } %>
      <%= f.input :active %>
	  <%# f.input :active, as: :radio_buttons %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>


  <!--times = @camp.time_slot == "am" ? [["Morning", "am"], ["Afternoon", "pm"]] : [["Afternoon", "pm"], ["Morning", "am"]]
      <%# f.select :time_slot, times, :prompt => "Select Time of Day..." %>-->

      
      

app/views/camps/_inactive_camps.html.erb
<% if @inactive_camps.empty? %>
  <h4>There are no inactive camps at this time.</h4>
<% else %>
  <h3>Inactive Camps</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>Time Slot</th>
      <th>Max Students</th>
      <th>Remaining Slots</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inactive_camps.each do |camp| %>
      <tr>
        <td><%= link_to camp.curriculum.name, camp %></td>
        <td><%= camp.start_date.strftime("%m/%d/%y") %></td>
        <td><%= camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
        <td><%= camp.max_students %></td>
        <td><%#camp.max_students - camp.registrations.count %></td>
        <td><%= link_to 'Edit', edit_camp_path(camp), :class=>"btn waves-effect waves-light blue" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<span class="paginate">
  <%= will_paginate @inactive_camps, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => 'inactive_camps' %>
</span>

app/views/camps/edit.html.erb
<div class="row">
  <div class="field col s12">
    <h1>Editing Camp</h1>
    <%= render 'form', camp: @camp %>
    <div class="row">
      <div class="field col s12">
        <%= link_to 'Show', @camp, :class=>"btn waves-effect waves-light" %>
      </div>
    </div>
  </div>
</div>

app/views/camps/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "camp", 
                                                         primary: "active_camps", 
                                                         secondary: "inactive_camps",
                                                         sidebar: nil} %>

app/views/camps/new.html.erb
<h1>New Camp</h1>

<%= render 'form', camp: @camp %>

app/views/camps/show.html.erb
<div class="row">
  <div class="col s7">
    <%= render :partial => "camp_details" %>
  </div>
  <div class="col s5">
    <%= render :partial => "camp_instructors"%>
    <%# render :partial => "camp_students"%>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <%= render :partial => "partials/object_options", locals: {model_name: "camp", object: @camp} %>
  </div>
</div>