config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :students
  resources :registrations
  resources :families
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :camps
  resources :camp_instructors
  resources :curriculums
  resources :instructors
  resources :locations
  
  get 'home', :to => 'home#home'
  get 'about', :to => 'home#about'
  get 'contact', :to => 'home#contact'
  get 'privacy', :to => 'home#privacy'
  
  root to: 'home#home'

end

app/models/family.rb
class Family < ApplicationRecord
    # relationships
    belongs_to :user
    has_many :students
    has_many :registrations, through: :students
    
    # validations
    validates_presence_of :family_name, :parent_first_name    
    
    # scopes
    scope :alphabetical, -> { order('family_name, parent_first_name') }
    scope :active, -> { where(active: true) }
    scope :inactive, -> { where(active: false) }
    
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:family_name, :parent_first_name, :user_id, :active)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= simple_form_for(@family) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :family_name %>
    <%= f.input :parent_first_name %>
    <%= f.input :user_id %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Families</h1>

<table>
  <thead>
    <tr>
      <th>Family name</th>
      <th>Parent first name</th>
      <th>User</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
      <tr>
        <td><%= family.family_name %></td>
        <td><%= family.parent_first_name %></td>
        <td><%= family.user_id %></td>
        <td><%= family.active %></td>
        <td><%= link_to 'Show', family %></td>
        <td><%= link_to 'Edit', edit_family_path(family) %></td>
        <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Family name:</strong>
  <%= @family.family_name %>
</p>

<p>
  <strong>Parent first name:</strong>
  <%= @family.parent_first_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @family.user_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @family.active %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>