config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :students
  resources :registrations
  resources :families
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :camps
  resources :camp_instructors
  resources :curriculums
  resources :instructors
  resources :locations
  
  get 'home', :to => 'home#home'
  get 'about', :to => 'home#about'
  get 'contact', :to => 'home#contact'
  get 'privacy', :to => 'home#privacy'
  
  root to: 'home#home'

end

app/models/instructor.rb
class Instructor < ApplicationRecord
  # relationships
  # belongs_to :user
  has_many :camp_instructors
  has_many :camps, through: :camp_instructors

  # validations
  validates_presence_of :first_name, :last_name

  # scopes
  scope :alphabetical, -> { order('last_name, first_name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :needs_bio, -> { where('bio IS NULL') }
  # scope :needs_bio, -> { where(bio: nil) }  # this also works...

  # class methods
  def self.for_camp(camp)
    # the 'instructive way'... (which I told you if you asked me for help)
    CampInstructor.where(camp_id: camp.id).map{ |ci| ci.instructor }
    # the easy way... 
    # camp.instructors
  end

  # callbacks
  # before_save :reformat_phone
  

  # instance methods
  def name
    last_name + ", " + first_name
  end
  
  def proper_name
    first_name + " " + last_name
  end

  # private
  # def reformat_phone
  #   phone = self.phone.to_s  # change to string in case input as all numbers 
  #   phone.gsub!(/[^0-9]/,"") # strip all non-digits
  #   self.phone = phone       # reset self.phone to new string
  # end
  
  

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  def index
    @instructors = Instructor.all.alphabetical.paginate(:page => params[:page]).per_page(12)
  end

  def show
    @past_camps = @instructor.camps.past.chronological
    @upcoming_camps = @instructor.camps.upcoming.chronological
  end

  def edit
  end

  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      redirect_to instructor_path(@instructor), notice: "#{@instructor.first_name} #{@instructor.last_name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @instructor.update(instructor_params)
      redirect_to instructor_path(@instructor), notice: "#{@instructor.first_name} #{@instructor.last_name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @instructor.destroy
    redirect_to instructors_url, notice: "#{@instructor.first_name} #{@instructor.last_name} was deleted from the system."
  end

  private
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name, :bio, :user_id, :email, :phone, :active)
    end
end

app/views/instructors/_form.html.erb
<%= simple_form_for(@instructor) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :first_name, label_html: { class: 'active' } %>
      <%= f.input :last_name, label_html: { class: 'active' } %>
      <%= f.input :bio, label_html: { class: 'active' } %>
      <%= f.input :email, label_html: { class: 'active' } %>
      <%= f.input :phone, label_html: { class: 'active' } %>
      <%# f.input :user_id, label_html: { class: 'active' } %>
      <%= f.input :active %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/instructors/_instructor_details.html.erb
<h3><%= @instructor.proper_name %></h3>

<h5>Basic Information</h5>
<p><strong>Bio: </strong><%= @instructor.bio %></p>
<p><strong>Email: </strong><%= @instructor.email %></p>
<p><strong>Phone: </strong><%= number_to_phone @instructor.phone %></p>
<p><strong>Active:</strong>
  <%= @instructor.active ? "Yes" : "No" %>
</p>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<% if @instructors.empty? %>
  <h3>There are no instructors in the system at this time</h3>
<% else %>
  <h3>Instructors</h3>

  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Camps</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= link_to instructor.name, instructor %></td>
        <td><%= number_to_phone instructor.phone %></td>
        <td><%= instructor.camps.size %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor), :class=>"btn waves-effect waves-light blue" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<span class="paginate">
  <%= will_paginate @instructors, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => 'instructors' %>
</span>

    <% end %>

<%= link_to 'New instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<div class="row">
  <div class="col s5">
    <%= render :partial => "instructor_details" %>
  </div>
  <div class="col s7">
    <%= render :partial => "partials/camps_list", locals: {camps: @upcoming_camps, state: "Upcoming"} %>
    <%= render :partial => "partials/camps_list", locals: {camps: @past_camps, state: "Past"} unless @past_camps.empty? %>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <%= render :partial => "partials/object_options", locals: {model_name: "instructor", object: @instructor} %>
  </div>
</div>