config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :students
  resources :registrations
  resources :families
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :camps
  resources :camp_instructors
  resources :curriculums
  resources :instructors
  resources :locations
  
  get 'home', :to => 'home#home'
  get 'about', :to => 'home#about'
  get 'contact', :to => 'home#contact'
  get 'privacy', :to => 'home#privacy'
  
  root to: 'home#home'

end

app/views/partials/_address_info.html.erb
<%= location.street_1 %><br />
<% unless location.street_2.blank? %>
	<%= location.street_2 %><br />
<% end %>
<%= location.city %>, <%= location.state %> <%= location.zip %>

app/views/partials/_camps_list.html.erb
<div class="card indigo lighten-2">
  <div class="card-content white-text">
    <span class="card-title"><%= state %> Camps</span>
    <% if camps.empty? %>
    <p>No camps at this time</p>
    <% else %>
      <table>
        <thead>
          <th>Name</th>
          <th>Place</th>
          <th>Starting</th>
        </thead>
          <% for camp in camps %>
            <tr>
              <td><%= link_to camp.name, camp_path(camp) %></td>
              <td><%= link_to camp.location.name, location_path(camp.location) %></td>
              <td>&nbsp;<%= camp.start_date.strftime("%m/%d/%y") %></td>
            </tr>
          <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div>
    <%= javascript_tag "Materialize.toast('#{msg}', 4000)" %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <%= link_to 'Home', home_path, :class => "grey-text text-lighten-3" %>&nbsp;&nbsp;::&nbsp;&nbsp;
      <%= link_to 'About the Chess Camp', about_path, :class => "grey-text text-lighten-3" %>&nbsp;&nbsp;::&nbsp;&nbsp;
      <%= link_to 'Contact Us', contact_path, :class => "grey-text text-lighten-3" %>&nbsp;&nbsp;::&nbsp;&nbsp;
      <%= link_to 'Privacy Policy', privacy_path, :class => "grey-text text-lighten-3" %>
      <br /><br />
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Webmaster: <%= mail_to("profh@cmu.edu", "Klingon Code Warrior", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2018
    </div>
  </div>
</footer>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="col s10 center">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>

  <br></br>
  <div class="col s3 center">
    <!-- Add a button for new instances of object -->
    <%= link_to(eval("new_#{model_name}_path"), class: "btn waves-effect waves-light blue") do %>
      <!-- <i class="fa fa-plus"></i> -->
      &nbsp;Add a New <%= model_name.capitalize %>
    <% end %>
  </div>
</div>

app/views/partials/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    &nbsp&nbsp
    <a href="/" class="brand-logo">A&M Chess Camp</a>
    <ul class="right">
      <li><%= link_to "Curriculums", curriculums_path %></li>
      <li><%= link_to "Camps", camps_path %></li> 
      <li><%= link_to "Instructors", instructors_path %></li>
      <li><%= link_to "Locations", locations_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:proper_name) ? object.proper_name : (object.respond_to?(:name) ? object.name : model_name.capitalize) }" %>

<div class="form-actions">
  <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
    &nbsp;Display All <%# model_name.pluralize.capitalize %>
  <% end %>
  &nbsp;&nbsp;
  
  <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
      &nbsp;<%= "Edit #{opt}" %>
  <% end %>
  &nbsp;&nbsp;
  
  <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
      &nbsp;<%= "Delete #{opt}" %>
  <% end %>
</div>